### ISSUE TITLE
bug: leverage bar selection

### ISSUE THREAD

**Issue by Zergity** [blackskin18/leverage-slider-comp#2]
![Image](https://user-images.githubusercontent.com/37166829/261514347-d877c7df-b260-4f06-b1c1-31b73c852af9.png)

Steps:
1. select 8x bar
2. select the top bar of 4x

Expected: the top bar to be selected
Actual: the bottom bar is selected

**Comment by jc-hello** [comment]
https://github.com/derivable-labs/leverage-slider-comp/commit/a453fd3f74b786d3c80fd76b17136c8449e815a4
